### ISSUE TITLE
cannot download osx driver

### ISSUE THREAD

**Issue by Jun-Yang** [Ardesco/selenium-standalone-server-plugin#24]
Failed to execute goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.7:selenium (default) on project org.bigtester.ate.core: Execution default of goal com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.7:selenium failed: Unrecognised operating system name 'osx' -> [Help 1]

**Comment by Ardesco** [comment]
Can you provide some more information, for example your POM and your RepositoryMap.xml.  I'm not seeing this error.

**Comment by Jun-Yang** [comment]
Hi  Mark,

Thanks for your answer. Please find bom file and repo.xml as attached.
Following is the detailed error information:

-------------------------------------------------------
[INFO]  DOWNLOADING SELENIUM STAND-ALONE EXECUTABLE BINARIES...
[INFO] --------------------------------------------------------
[INFO]
[INFO]
file:/C:/Users/Jun/git/automation-test-engine/org.bigtester.ate.core/browserdriver/repo.xml
is valid
[INFO]
[INFO] Only get drivers for current Operating System: false
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 11.722 s
[INFO] Finished at: 2015-05-12T15:52:04-04:00
[INFO] Final Memory: 22M/356M
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.7:selenium
(default) on project org.bigtester.ate.core: Execution default of goal
com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.7:selenium
failed: Unrecognised operating system name 'osx' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Best regards

Jun Yang


2015-05-12 2:38 GMT-03:00 Mark Collin <notifications@github.com>:

**Comment by Ardesco** [comment]
I don't see a POM file or a repository map.xml.  If you replied to a notification e-mail my guess would be that gitHub has stripped them out.  Could you add then to the issue on GitHub please.

**Comment by Jun-Yang** [comment]
POM File:	
<groupId>com.lazerycode.selenium</groupId>
				<artifactId>driver-binary-downloader-maven-plugin</artifactId>
				<version>1.0.7</version>
				<configuration>
					
					<rootStandaloneServerDirectory>browserdriver</rootStandaloneServerDirectory>
					
					<downloadedZipFileDirectory>/tmp/zips</downloadedZipFileDirectory>
					
					<customRepositoryMap>browserdriver/repo.xml</customRepositoryMap>
					
					<onlyGetDriversForHostOperatingSystem>false</onlyGetDriversForHostOperatingSystem>
					
					<operatingSystems>
						<windows>true</windows>
						<linux>true</linux>
						<osx>true</osx>
					</operatingSystems>
					
					<thirtyTwoBitBinaries>true</thirtyTwoBitBinaries>
					
					<sixtyFourBitBinaries>true</sixtyFourBitBinaries>
					
					<onlyGetLatestVersions>true</onlyGetLatestVersions>
					
					
					
					
					
					<throwExceptionIfSpecifiedVersionIsNotFound>false</throwExceptionIfSpecifiedVersionIsNotFound>
					
					<fileDownloadRetryAttempts>2</fileDownloadRetryAttempts>
					
					<fileDownloadConnectTimeout>20000</fileDownloadConnectTimeout>
					
					<fileDownloadReadTimeout>10000</fileDownloadReadTimeout>
					
					<overwriteFilesThatExist>true</overwriteFilesThatExist>
					
					<checkFileHashes>true</checkFileHashes>
					
					
					<useSystemProxy>true</useSystemProxy>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>selenium</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

repo.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<root>
    <windows>
        <driver id="internetexplorer">
            <version id="2.45.0">
                <bitrate sixtyfourbit="true">
                    <filelocation>http://selenium-release.storage.googleapis.com/2.45/IEDriverServer_x64_2.45.0.zip</filelocation>
                    <hash>b3cdacc846d7b9c3f8fb8b70af0a9cfc5839bd83</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
                <bitrate thirtytwobit="true">
                    <filelocation>http://selenium-release.storage.googleapis.com/2.45/IEDriverServer_Win32_2.45.0.zip</filelocation>
                    <hash>cc822d30efe3119b76af9265c47d42fca208f85a</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
        <driver id="googlechrome">
            <version id="2.15">
                <bitrate thirtytwobit="true" sixtyfourbit="true">
                    <filelocation>http://chromedriver.storage.googleapis.com/2.15/chromedriver_win32.zip</filelocation>
                    <hash>23d8c1a6a96f85f21f5b06c7df1000dd82e0d3be</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
         <driver id="operachromium">
            <version id="0.2.2">
                <bitrate sixtyfourbit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_win64.zip</filelocation>
                    <hash>8b84d334ca6dc5e30c168d8df080c1827e4c6fdb</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>      
                <bitrate thirtytwobit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_win32.zip</filelocation>
                    <hash>daa9ba52eeca5ea3cb8a9020b85642ec047e9890</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>    
            </version>
        </driver>
    </windows>
    <linux>
        <driver id="googlechrome">
            <version id="2.15">
                <bitrate sixtyfourbit="true">
                    <filelocation>http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip</filelocation>
                    <hash>ebc3e490e9a91497377b8d04e4c8b7ab4020674f</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
                <bitrate thirtytwobit="true">
                    <filelocation>http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux32.zip</filelocation>
                    <hash>419c9689ccf176df6dd76fa233e91c269b31644c</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
        <driver id="operachromium">
            <version id="0.2.2">
                <bitrate sixtyfourbit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_linux64.zip</filelocation>
                    <hash>c207c6916e20ecbbc7157e3bdeb4737f14f15fe3</hash>
                    <hashtype>sha1</hashtype> 
                </bitrate>
                <bitrate thirtytwobit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_linux32.zip</filelocation>
                    <hash>8b0b92a870a1b4ba619eb0b85ec587caa2942e5b</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
    </linux>
    <osx>
        <driver id="googlechrome">
            <version id="2.15">
                <bitrate thirtytwobit="true" sixtyfourbit="true">
                    <filelocation>http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip</filelocation>
                    <hash>2c7cb03dff95f37f2558f42d2c0521098e24f27f</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
       <driver id="operachromium">
            <version id="0.2.2">
                <bitrate sixtyfourbit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_mac64.zip</filelocation>
                    <hash>d58a3b676dda7ede5c38e5df218e7c619495c4ed</hash>
                    <hashtype>sha1</hashtype> 
                </bitrate>
                <bitrate thirtytwobit="true">
                    <filelocation>https://github.com/operasoftware/operachromiumdriver/releases/download/v0.1.0/operadriver_mac32.zip</filelocation>
                    <hash>7ab79a1c70bb0f5998b9c5c8d08160ef86b618e9</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
    </osx>
</root>

**Comment by Ardesco** [comment]
What operating system are you using?

**Comment by Jun-Yang** [comment]
Windows 7

**Comment by Ardesco** [comment]
Can you try setting:

    <operatingSystems>
        <windows>true</windows>
        <linux>true</linux>
        <mac>true</mac>
    </operatingSystems>

**Comment by Jun-Yang** [comment]
Now, it works. I change <osx> to <mac>.

I dont need to change <osx> to <mac> in repo.xml?

**Comment by Jun-Yang** [comment]
do I need to change in repo.xml?

**Comment by Jun-Yang** [comment]
do I need to change osx to mac in repo.xml?

**Comment by Ardesco** [comment]
Nope, it's a documentation bug, the RepositoryMap.xml spec hasn't changed.

Basically I forgot to check that the documentation is correct for 1.0.6 and 1.0.7.

**Comment by Jun-Yang** [comment]
Ok, thanks a lot.

**Comment by mraphael2101** [comment]
Works like a treat.
