### ISSUE TITLE
Firefox driver is not support

### ISSUE THREAD

**Issue by zhenghu** [Ardesco/selenium-standalone-server-plugin#25]
A very useful plugin for automating selenium testing.
But I can not figure out how to use this plugin to use firefox driver though the firefox is the default browser.

**Comment by Ardesco** [comment]
FirefoxDriver does not need an external binary so there is nothing to download for Firefox.

All this plugin does is download standalone binaries and set a variable that selenium can use to locate them.

**Comment by volkertb** [comment]
Although this is true for the current generation FirefoxDriver, it is intended to be succeeded by the MarionetteDriver, which does in fact require an external binary. I took the liberty of creating a separate issue requesting support for the MarionetteDriver: https://github.com/Ardesco/selenium-standalone-server-plugin/issues/34
