### ISSUE TITLE
Always downloads binary, even if previously downloaded

### ISSUE THREAD

**Issue by jnyman** [Ardesco/selenium-standalone-server-plugin#29]
It's not clear to me if this is an issue or not. I notice that I'll see the following output on every test run:

    [INFO] Preparing to download Selenium Standalone Executable Binaries...
    [INFO] Downloading  'chromedriver_mac32.zip'...
    [INFO] Archive file 'chromedriver_mac32.zip' is valid : true
    [INFO] Binary 'chromedriver' Exists: true

If I'm understanding this correctly, it seems like the binary is being downloaded each time. Maybe this doesn't matter in the long run but sometimes testing is done on a purely local version of an environment. 

For example, developers may run initial tests when they are connected (thus downloading the binaries). But then take their laptops with them and, even when not connected, run tests against a local version of the web application. That won't work, however, because the binaries are downloaded each time.

I'm not sure, but would it make sense to have it check if the binaries are already downloaded and, if so, simply use the existing if the existing matches what's in the RepositoryMap.xml?

**Comment by Ardesco** [comment]
The binary will only be downloaded if there is no local copy matching the SHA1/MD5 hash in the RepositoryMap.xml.

If you store your downloaded binaries in a place that gets cleaned out (e.g. your target directory) very time the build is run then it will be downloading them every time.

I guess the fix would be to make the logging slightly clearer

**Comment by Ardesco** [comment]
Enhancement is to improve logging to make it clearer that a file is not downloaded if one already exists.
