### ISSUE TITLE
Please add support for Firefox Marionette (the "wires" binary)

### ISSUE THREAD

**Issue by volkertb** [Ardesco/selenium-standalone-server-plugin#34]
The next generation of the FirefoxDriver, currently called MarionetteDriver, also requires an external standalone server binary in order to work. The server binary is called "wires" and is available for Windows, Linux and Mac OS X.

Please add support for MarionetteDriver to this plugin, so that the "wires" executable can also be automatically downloaded by this plugin. Even though the (old/current) FirefoxDriver driver is still available for the time being, as I understand it, the MarionetteDriver is meant to eventually replace it. It would be nice to have support for it in place well beforehand.

For more information regarding Marionette, see these links:

- https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette
- https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

Thank you in advance for considering this feature enhancement request.

Excellent plugin, by the way! :-) I like the idea of having a one-stop-shop for all required external sever executables for running Selenium tests with different browsers. It saves a lot of manual configuration work.

**Comment by Ardesco** [comment]
Having a quick, look it's going to take a bit of fiddling.

- Marionette doesn't seem to have a specific system property is check for the binary location, instead it expects you to add it to the path.
- The file you extract from the downloaded archives has the version number in the filename which makes it a little bit more awkward than the rest of the standalone drivers.

**Comment by volkertb** [comment]
Thanks for the quick response! In reply to both of your points:

- Perhaps an upstream feature request can be opened for the MarionetteDriver to support an optional explicit binary path in a system property.
- Nothing a regular expression couldn't fix, right? :-)

**Comment by Ardesco** [comment]
It shouldn't be a big deal, I've been busy moving the build stuff over to Travis and Rultor this weekend so I haven't had a change to look at it yet. 

I can set a property that provides you with the marionette driver location anyway, it just won't automatically be picked up so you'll need to explicitly consume that property to set the binary location.  It's not the end of the world, it's just a little more config in your Selenium scripts.

I'm asking around at the moment.

**Comment by Ardesco** [comment]
@rultor release, tag is `1.0.9`

**Comment by volkertb** [comment]
Excellent work! Thank you for implementing this so quickly. :-)
