### ISSUE TITLE
Add support for Safari webdriver

### ISSUE THREAD

**Issue by bitwiseman** [Ardesco/selenium-standalone-server-plugin#39]
Safari is not listed in the BinaryType Enum

**Comment by Ardesco** [comment]
Is there a downloadable SafariDriver binary yet?  It used to be built into selenium until Safari removed the ability to use unsigned plugins.  I'm not aware of a repository that you can download it from.

**Comment by bitwiseman** [comment]
Here's one link: 
http://selenium-release.storage.googleapis.com/2.48/SafariDriver.safariextz

It looks like the drive isn't in every release:
Does not have driver: http://selenium-release.storage.googleapis.com/index.html?path=2.47/
Has driver: http://selenium-release.storage.googleapis.com/index.html?path=2.48/
Does not have driver: http://selenium-release.storage.googleapis.com/index.html?path=2.49/

**Comment by Ardesco** [comment]
I'll have to check but I think that's around the time the binaries needed to be signed to be able to be see in safari

**Comment by Ardesco** [comment]
This is not needed now.  As soon as you update to Safari 10 you will find a `/usr/bin/safaridriver` installed on your system.  I'm going to close this as a result.

**Comment by bitwiseman** [comment]
@Ardesco - what about on systems not running safari 10?  Testing only on safari 10+ is not really how Selenium is used.

**Comment by Ardesco** [comment]
The only official support for Safari depends on you running Safari 10.  Apple is very good at dropping support for legacy software quickly, and they are very good at getting people to upgrade to new versions of software.  The longer you leave it the less relevant Safari 9 is going to be.  

SeleniumHQ has Safaridriver 2.48.0 as the last supported version.  The most recent 2.x version of Selenium is v2.53.0, and we are currently on the 3.0.0 betas

What you are really asking for is a way to support old unofficial deprecated versions of SafariDriver for old versions of Selenium.  I don't think it's worth the time or effort to add this in.

**Comment by bitwiseman** [comment]
@Ardesco - Okay, I get it. Thanks for the explanation.
