### ISSUE TITLE
Add support for Firefox esr binaries

### ISSUE THREAD

**Issue by angiekollmer** [Ardesco/selenium-standalone-server-plugin#41]
My selenium project currently will not work with marionette driver.  Instead I have downloaded the exe for Firefox Extended Support Release version and I have the path to the binary hard coded and I create the firefox driver like this:

```
FirefoxBinary binary = new FirefoxBinary(pathToBinary);
instance  = new FirefoxDriver(binary, profile);
```

Is there a way to use this plugin for the esr binary?

**Comment by Ardesco** [comment]
On pre-marionette versions of Firefox you don't need to download anything, FirefoxDriver is built into selenium.  you will however need to use an older version of Selenium if the FirefoxDriver has been removed in newer versions of Selenium.
