### ISSUE TITLE
Downloaded drivers are not executable.

### ISSUE THREAD

**Issue by mcdonnell-john** [Ardesco/selenium-standalone-server-plugin#42]
Just found this plugin and have set it up against my project, but the drivers are not executable.

I found [1] and it seems you pushed out version 0.91 with this feature, but it seems to have disappeared?

$ ls -lrt /Users/john/codebase/project/selenium-e2e/selenium_standalone/osx/googlechrome/64bit/
total 13520
-rwxr--r--  1 john  staff  6919952 24 Oct 20:45 chromedriver

 [1]: http://ardesco.lazerycode.com/index.php/2012/08/introducing-the-driver-binary-downloader-maven-plugin-for-selenium/

**Comment by Ardesco** [comment]
hmm that's strange.

Can you show me your POM and let me know what OS you are using.

**Comment by mcdonnell-john** [comment]
I have added this plugin configuration at the moment:
<plugin>
                <groupId>com.lazerycode.selenium</groupId>
                <artifactId>driver-binary-downloader-maven-plugin</artifactId>
                <version>1.0.11</version>
                <configuration>
                    <rootStandaloneServerDirectory>${standalone.binary.root.folder}</rootStandaloneServerDirectory>
                    <downloadedZipFileDirectory>${project.basedir}/src/test/resources/selenium_standalone_zips</downloadedZipFileDirectory>
                    <customRepositoryMap>${project.basedir}/src/test/resources/RepositoryMap.xml</customRepositoryMap>
                    <overwriteFilesThatExist>${overwrite.binaries}</overwriteFilesThatExist>
                    <checkFileHashes>false</checkFileHashes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>selenium</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

and I am using mac osx (el capitan)

**Comment by mcdonnell-john** [comment]
Not sure but maybe using Files.setPosixFilePermissions(Path path, Set<PosixFilePermission> perms) might be an alternative option, to using File.setExecutable()?

**Comment by mcdonnell-john** [comment]
This was an error in my resourcemap file :(  Sorry.

**Comment by Ardesco** [comment]
Glad to hear you got it sorted :)
