### ISSUE TITLE
NullPointer exception in setRepositoryMapFile()

### ISSUE THREAD

**Issue by GadgetMan0101** [Ardesco/selenium-standalone-server-plugin#51]
Using version 1.0.11

` java.lang.NullPointerException
	at com.lazerycode.selenium.SeleniumServerMojo.setRepositoryMapFile(SeleniumServerMojo.java:290)
	at com.lazerycode.selenium.SeleniumServerMojo.execute(SeleniumServerMojo.java:193)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)`

It looks like the `checkRepositoryMapIsValid()` method sets the `customRepositoryMap` field to `null` after it receives the `IOException` "java.net.ConnectException: Connection timed out: connect" when trying to validate the xmlFile.

I had added a `DOCTYPE` to my `RepositoryMap.xml` in an attempt to remove an eclipse validation warning. The DOCTYPE is what caused the connect time-out.
`<!DOCTYPE root PUBLIC "-"
          "https://github.com/Ardesco/selenium-standalone-server-plugin/blob/master/src/main/resources/RepositoryMap.xsd">`

I've removed it, which solves that problem, but thought I would point out the exception.

**Comment by Ardesco** [comment]
Thanks for the bug report, one for the next release.

**Comment by Ardesco** [comment]
Fixed with changes made to fix #57
