### ISSUE TITLE
Support for (standalone) browser download

### ISSUE THREAD

**Issue by Hi-Fi** [Ardesco/selenium-standalone-server-plugin#52]
There's currently possibility to download only PhantomJS as complete browser. There're portable packages of Firefox and Google Chrome available, which could be used same way as PhantomJS in testing and same time be sure that there's no version incompatibility with Selenium.

New drivers could be at least:
- firefox (environment property pointing to firefox binary: webdriver.firefox.bin)
- googlechrome

**Comment by Ardesco** [comment]
Sounds like a good idea

**Comment by Hi-Fi** [comment]
Any comments? That PR should make the trick.
