### ISSUE TITLE
file hash doesn't coincide with expected while downloading artifact via https

### ISSUE THREAD

**Issue by Al-Pro** [Ardesco/selenium-standalone-server-plugin#53]
Hi all,

While I'm trying to download an artifact from local repository via https I get the following error:
[ERROR] File : 'chromedriver_linux64.zip'.
[ERROR] Expected file hash : '025a098cde0a6ad8aef53d6734979c9845bf49b5'.
[ERROR] Actual file hash   : 'fe1f6c9fb1e46f147c2ba08322f182bedc3d4103'.
[INFO] Archive file 'chromedriver_linux64.zip' is valid : false
[INFO] Problem downloading 'chromedriver_linux64.zip'... 
whereas downloading this zip via http is always successful.

I tried to find similar issues related to the plugin but failed what's more in the example of the repository mapping file there is https defined. So I may conclude that it should work.
Could you please help me to figure out what could be wrong and how I can try to solve an issue?

Thank you very much indeed,
Alex

**Comment by Ardesco** [comment]
If the hash is failing it means that the file you have downloaded is not the file that the plugin was expecting to download.

You can compare the files manually by doing the following:

- Download the file from https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
- Open a terminal and navigate to the directory in which the file has been downloaded
- Type `openssl sha1 chromedriver_linux64.zip`

This is the SHA1 hash of the file downloaded from google, save this we will need it later.

Next do the following:

- Download the file from your local repository
- In the terminal navigate to the directory in which the file has been downloaded
- Type `openssl sha1 chromedriver_linux64.zip`

This is the SHA1 hash of the file downloaded from your local repository.  If the SHA1 hashes are different you have 2 different files.  If this is the case you will either need to update your RepositoryMap.xml to expect the hash for the file you have downloaded from your local repository, or copy the file you have downloaded from google to your local repository.

**Comment by Al-Pro** [comment]
It's a magic, not less than. :) 
Didn't change anything but now it works. Thank you so much and really sorry for disturbing you.
