### ISSUE TITLE
Investigate generation of hash

### ISSUE THREAD

**Issue by haroon-sheikh** [Ardesco/selenium-standalone-server-plugin#71]
We currently use this on Linux/Windows/Mac and it's a bit of task to get hashes for each OS when a new driver becomes available.

We should investigate an easiest way to get these hashes?

**Comment by Ardesco** [comment]
the only option I can think of is to have a remote file stored somewhere that tries to get pulled down by default that lists every version of the driver with appropriate hashes.

This will still go stale if it's not kept up to date.

You can turn off hash checks, but then you will not know if you have downloaded a correct file.
