### ISSUE TITLE
Won't download specific drivers mentioned on RepositoryMap.xml

### ISSUE THREAD

**Issue by Ben-Mark** [Ardesco/selenium-standalone-server-plugin#72]
My goal is to download specific drivers only.
I thought by mentioning on the RepositoryMap.xml my desired drivers, it would only download them.
instead it downloads them all

What am I doing wrong?
Is this a bug? #

**Comment by Ardesco** [comment]
Can you paste your plugin config

**Comment by Ben-Mark** [comment]
even though I proveded the RepositoryMap.xml
Do I need to provide as well the following configuration: ???
 <getSpecificExecutableVersions>
                    <googlechrome>18</googlechrome>
 </getSpecificExecutableVersions>

etc..?

**Comment by Ardesco** [comment]
The way the plugin is configured will determine which parts of the RepositoryMap.xml is read and which files are downloaded.

If you share the plugin config you have in your POM file I can see what settings you have and I can try and reproduce your problem.

**Comment by Ben-Mark** [comment]
solved it by changing to the version 1.0.16
