### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by yahmedov** [Ardesco/selenium-standalone-server-plugin#83]
I just tried using `WebDriverManager.chromedriver().setup();`
to handle the chromedriver, instead of downloading it and setting its path.

The WebDriverManager seems to be working fine, but I'm getting 

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Do i really need SLF4J and how can I fix the error?

**Comment by Ardesco** [comment]
I think you want https://github.com/bonigarcia/webdrivermanager

**Comment by yahmedov** [comment]
I was asking how to fix an issue with https://github.com/bonigarcia/webdrivermanager
why are you just copy pasting the link?

Is this how you support your code, that's lame.

**Comment by Ardesco** [comment]
That's not my code, it's an entirely different project.  I've tried pointing you to the correct place to answer questions about that code.

The code in this repository is a maven plugin that downloads driver binaries for you.  If you are using webdrivermanager you do not need to use a maven plugin to download binaries.

**Comment by yahmedov** [comment]
Ah, ok then.
No idea why i submitted the issue here.
